---
output: 
  html_document:
    theme: "spacelab"
---
#### Data Source

The data used by this tool was produced by the Seattle Office of Planning and Community Development during their 2015 Development Capacity analysis (released Spring 2015).

The original file can be found here: <https://data.seattle.gov/api/views/n2mk-9di2/rows.csv?accessType=DOWNLOAD>

*** 

#### Disclaimers

The City of Seattle would like all users of their data products to know the following:
    
> The data made available here has been modified for use from its original source, which is the City of Seattle. Neither the City of Seattle nor the Office of the Chief Technology Officer (OCTO) makes any claims as to the completeness, timeliness, accuracy or content of any data contained in this application; makes any representation of any kind, including, but not limited to, warranty of the accuracy or fitness for a particular use; nor are any such warranties to be implied or inferred with respect to the information or data furnished herein. The data is subject to change as modifications and updates are complete. It is understood that the information contained in the web feed is being used at one's own risk.